### ISSUE TITLE
[opnsynid_asset_account] Error ketika membuka menu Companies

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/opnsynid-accounting-report#33]
Cara reproduki bugs:
1. Buka menu **Setting->Company->Companies**
2. Buka salah satu data company

Pesan error:
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1545, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 841, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 369, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `default_cutoff_journal_id` does not exist

Error context:
View `res.company.form`
[view_id: 111, xml_id: base.view_company_form, model: res.company, parent_id: n/a]

**Comment by andhit-r** [comment]
Close with 602a9371ba99d29dba5939dff9751201a297690b
